wpilibsuite/RobotBuilder

src/main/resources/export/cpp/ExportDescription.yaml, src/main/resources/export/java/ExportDescription.yaml
Previously it inherited from AnalogInput and used GetAverageVoltage
which doesn't exist for AnalogAccelerometer. Change to use
GetAcceleration
=> Fix export of AnalogAccelerometer when used with a PIDSubsystem

src/main/resources/export/cpp/RobotMap-allocation.cpp, src/main/resources/export/cpp/Subsystem.h
RobotMap Allocations had export had frc::frc::
Subsystems would have been broken for extensions not in frc
namespace.
=> Fix a few instances of frc namespace

src/main/resources/PaletteDescription.yaml
Conditional Commands didn't have a parameter preset field which
caused the OI export to fail.
=> Fix export of Conditional Commands to SmartDashboard

src/main/resources/export/java/.classpath
This ensures you don't have to close and reopen eclipse before you
can use opencv/cscore.
=> Update classpath with opencv, cscore, and wpiutil

src/main/resources/export/java/ExportDescription.yaml, src/main/resources/export/java/Subsystem-constructors.java
The C++ ExportDescription.yaml still use the LiveWindow addSensor, The Java ExportDescription.yaml uses the addChild only it only passes one parameter. The result is all the objects on the LiveWindow tab titles the object with the type name. Passing two parameters results in the object having descriptive titles. 
The other file Subsystem-constructors.java adding the extra space creates a white space if the component has an #extra parameter it will have a empty line between the next component.
=> Re-add the Name parameter that was added in the past with LiveWindow

src/main/resources/export/cpp/settings.json, src/main/resources/export/java/settings.json
RobotBuilder backups have a ~ at the end, exclude '**/*~'
=> Exclude RobotBuilder backup files from VSCode File Explorer

src/main/resources/export/cpp/ExportDescription.yaml, src/main/resources/export/cpp/Subsystem-declarations.h
use export declarations for subsystem-declerations.h
Don't add frc namesspace for CustomComponents
Fixes #194
=> Fix frc namespace for CustomComponents

.github/workflows/gradle-wrapper-validation.yml
A side effect of this PR is that it will enable changes to the Actions Workflows to trigger as part of the PR process (#249). We use this same wrapper validation workflow in other repos.
=> Run Gradle Wrapper validation on PRs

.gitignore, build.gradle, src/test/java/robotbuilder/SavingAndLoadingTest.java, src/test/java/robotbuilder/TestUtils.java, src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
Fixes #252
Also fully excludes test-resources in .gitignore for existing files
excludes vendordeps generated folder
=> Move test-resources folder to build

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit f8c0014078645a3db51e9c7c58a82889ccd4402f.
=> Revert "Disable compile tests until 2021 beta 1 gradlerio is released"

src/main/java/robotbuilder/robottree/RobotTree.java
One of my annoyances while using robot builder is even though I named my project at the start of a new project I have to retype the name on the first save. This should fix that.
=> Populate File Save Name

src/main/resources/export/cpp/ExportDescription.yaml, src/main/resources/export/cpp/Subsystem-declarations.cpp
Fixes #303
Revert changes to CustomComponent declaration to avoid breaking
extensions. Extensions that want to do initialization in the header like
the built-in objects can override the declaration field.
Restore export of construction field in subsystem. This is not used in
built-in objects but may be needed for extensions.
=> Fix export of C++ extensions

src/main/java/robotbuilder/ParameterSetsTable.java
Reverts part of #294 because the parameter set validation occurs on a
character by character basis. The entire parameter is still validated
elsewhere, so it doesn't need to be done here.
Fixes #321
=> Fix parameter set validation

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 05de066be3c9029b28bfdb707c1c005134b16209.
=> Revert "Disable compile tests until 2021 gradlerio is released"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 96cf5f4710fccea2c5d15931013e13d79f415685.
=> Revert "Disable compile tests until 2021 gradlerio is released (#347)"

src/main/resources/export/cpp/ExportDescription.yaml, src/main/resources/help/Xbox Button.html, src/test/java/robotbuilder/TestUtils.java
Fixes #368
Fix Test
Update Help
=> Fix C++ Export of XboxControllerButton

src/main/resources/export/cpp/RobotContainer-declarations.h, src/main/resources/export/cpp/RobotContainer-prototypes.h, src/main/resources/export/java/RobotContainer-declarations.java
Allows commands that don't require the subystem to access them (Fixes #367), This also allows commands to require multiple subystems and avoids huge dependency chains for CommandGroups.
=> Make subsystems public in RobotContainer

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit fb15e7854f33945b0a2991bd148a91ac0d6ef57a.
=> Revert "Disable compile tests until 2021 gradlerio is released (#390)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit c4923764162758924d1026c71d01bc78ec231b04.
=> Revert "Disable compile tests until 2021 gradlerio is released (#393)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit a8238a5bd24236bfc232239404b0a5347ad77398.
=> Revert "Disable compile tests until 2022 gradlerio is released (#407)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit ef47614ca7d2efaf8c7a51150d0734bca8ca2375.
=> Revert "Disable compile tests until 2022 gradlerio is released (#410)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 7c8d5989d73c9e97ec909ac21d65c87c6de405af.
=> Revert "Disable compile tests until 2022 gradlerio is released (#427)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 0ee917f88ea05bb0aa216649bc8004da3da067bf.
=> Revert "Disable compile tests until 2022 gradlerio is released (#434)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit a9f8e4d85f20cf8c53df878c8725454ce8455499.
=> Revert "Disable compile tests until 2022 gradlerio is released (#449)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit aded61f3de46fb8b6415a45e3a2804976131338a.
=> Revert "Disable compile tests until 2022 gradlerio is released (#456)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 53c47dfc045b0671a201406c907b0e43c2a5e765.
=> Revert "Disable compile tests until 2022 gradlerio is released (#460)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 8747f19b68b463296072615c529e604a56f45733.
=> Revert "Disable compile tests until 2022 gradlerio is released (#468)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit c535dbbc5a45da68fad4e834110cb6110d52bc34.
=> Revert "Disable compile tests until 2023 gradlerio is released"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 1e982166d6dc8dc597e698d8541f262ae11d386b.
=> Revert "Disable compile tests until 2023 gradlerio is released (#494)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 08f36cc8db17e2452fa8cad0afe41b6e6df81791.
=> Revert "Disable compile tests until 2023 gradlerio is released (#499)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 6bc9e49c1e90a2bcb1248dbf3088c042ce6b1128.
=> Revert "Disable compile tests until 2023 gradlerio is released (#512)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 46790ef81383e248b2dc5966b60db17b2f847f01.
=> Revert "Disable compile tests until 2023 gradlerio is released (#516)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 2deb8676b6c2d3492f00f28faba6d50af2e55026.
=> Revert "Disable compile tests until 2023 gradlerio is released (#521)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 4a9026ce88e5c5efc62716a1b7d9e55247a130e8.
=> Revert "Disable compile tests until 2023 gradlerio is released (#526)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit b2e518531491d447bb9450ad35cd5d625488ead1.
=> Revert "Disable compile tests until 2023 gradlerio is released (#531)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit af1e91acea1009887f865de38126460f1aa1166e.
=> Revert "Disable compile tests until 2023 gradlerio is released (#536)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 2fa59e5826c02c1fe017cbaf8c77c756acac48ad.
=> Revert "Disable compile tests until 2024 GradleRIO released"

src/main/resources/export/gradle/settings.gradle
Matches wpilibsuite/vscode-wpilib#617
=> Workaround for gradle rebuilding headers in C++ user projects

src/main/resources/export/cpp/build.gradle, src/main/resources/export/java/build.gradle, src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
Disable compile tests because c++ is broken until the next gradlerio release
Since compile tests are disabled, revert using development builds since they won't be needed when the next gradlerio is released.
Should be rebase merged so that compile test commit can be reverted.
=> Disable compile tests and don't use development builds

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 9cfdffd49c55c5f85dc47b80bff1dcdf80f66935.
=> Revert "Disable compile tests until 2024 GradleRIO released (#561)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit b0b023e5645c861e303abc17008203d9ef8e94a9.
=> Revert "Disable compile tests until 2024 GradleRIO released  (#565)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 551dfa58644f8b6440413016545db903a3fa960f.
=> Revert "Disable compile tests until 2024 GradleRIO released (#573)"

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 0443c66c32c70867b6df40674bd89cb33fbce9df.
=> Revert "Disable compile tests until 2024 GradleRIO released (#588)"

src/main/resources/export/cpp/CommandBasedRobot.cpp, src/main/resources/export/cpp/CommandBasedRobot.h, src/main/resources/export/java/RobotTemplate.java
See https://github.com/wpilibsuite/allwpilib/issues/6845
=> Remove robotInit in favour of Robot constructor

src/main/resources/export/java/RobotTemplate.java
Matches wpilibsuite/allwpilib#6892
=> Update Java Robot Template class comment (NFC)

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 36f0621e7a021059fdadeb5938c37a481c75882a.
=> Revert "Disable compile tests until GradleRIO released (#612)"

src/main/resources/export/cpp/settings.json
Fixed in CPP extension 1.22.9
This reverts commit c2143e57488bfdd81bec108ae1f92f6128d37c5b.
=> Revert "Add case sensitive file support to C++ projects (#620)"

gradle/wrapper/gradle-wrapper.properties, src/main/resources/export/gradle/wrapper/gradle-wrapper.properties
Needs wpilibsuite/GradleRIO#761 to avoid deprecation warnings
Matches wpilibsuite/vscode-wpilib#724
=> Update to Gradle 8.11

src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
This reverts commit 5d1459ee06498f4640098f20c485c4f812ff1c2f.
=> Revert "Disable compile tests until GradleRIO released (#634)"
