wpilibsuite/RobotBuilder

build.gradle
As detailed in wpilibsuite/design-docs#5. This will start at version 2.0.0.
=> Moved to using the wpilib versioning plugin

src/main/resources/export/parsers.yaml
Fixes Issue #15, by making the regex in parsers.yaml a little smarter.
=> resolve classes that implement interfaces issue #15

src/main/resources/export/java/RobotTemplate.java
=> Fix comment about updating class or package

src/main/resources/PaletteDescription.yaml, src/main/resources/help/Speed Controller.html
Changes to match https://github.com/wpilibsuite/allwpilib/pull/656
=> Changes TalonSRX to PWMTalonSRX

src/main/resources/export/cpp/files.yaml
=> fix export of TimedCommand

src/main/resources/PaletteDescription.yaml, src/main/resources/export/cpp/CommandBasedRobot-constructors.cpp, src/main/resources/export/cpp/ExportDescription.yaml, src/main/resources/export/java/ExportDescription.yaml, src/main/resources/export/java/RobotTemplate-constructors.java, src/main/resources/export/java/RobotTemplate.java
=> Add option to put Subsystems and PIDControllers to SmartDashboard

src/main/resources/export/cpp/ExportDescription.yaml
Fixes subsystem (missing frc namespace) and DoubleSolenoid
(extra frc namespace).
=> more frc namespace fixes

src/main/java/robotbuilder/ParameterSetsTable.java
=> Validate the name of a Parameter Set

src/main/java/robotbuilder/actions/ExporterAction.java, src/main/java/robotbuilder/exporters/ExportFile.java, src/main/java/robotbuilder/exporters/GenericExporter.java
So the user will know to close and reopen eclipse.
Helps with #83
=> Display message when project is exported for the first time

src/main/resources/export/cpp/CommandBasedRobot.cpp, src/main/resources/export/cpp/ExportDescription.yaml, src/main/resources/export/java/ExportDescription.yaml, src/main/resources/export/java/RobotTemplate.java
Change subsystem name in LiveWindow calls to match what robot code generates automatically
Add missing LiveWindow calls
Remove calls to LiveWindow Run
Fixes #88
=> Updates for 2018 LiveWindow changes

src/main/resources/export/cpp/CommandBasedRobot.cpp, src/main/resources/export/cpp/CommandBasedRobot.h
=> Fix C++ compile

src/main/java/robotbuilder/exporters/ExportFile.java
Only trigger if  a new directory is actually created, not any new file
=> Fix new project detection 

src/main/java/robotbuilder/RobotBuilder.java
=> Force GTK2

src/main/java/robotbuilder/RobotBuilder.java, src/main/resources/help/Robot.html
Fix 1 reference to Eclipse and fixes WPILib version in about
=> Misc fixes for 2019

src/main/java/robotbuilder/exporters/GenericExporter.java, src/main/resources/export/cpp/settings.json, src/main/resources/export/java/settings.json
Remove wpilib.online from settings.json
=> Update for 2019.2.1

src/main/resources/export/cpp/Subsystem-includes.cpp, src/main/resources/export/cpp/files.yaml
=> Fix default command include path.

src/main/resources/export/cpp/ExportDescription.yaml, src/main/resources/export/cpp/Subsystem-declarations.cpp
Fixes #125. The LiveWindow and Extra calls were lost in
commit c674322cc4d25
=> Re-enable export to LiveWindow in C++.

src/main/resources/PaletteDescription.yaml, src/main/resources/help/Speed Controller.html
Update links to speed controllers and remove unneeded uses of PWM
=> Add PWMSParkMax

src/main/resources/help/Analog Input.html, src/main/resources/help/Analog Potentiometer.html, src/main/resources/help/AnalogAccelerometer.html, src/main/resources/help/AnalogGyro.html, src/main/resources/help/Differential Drive.html, src/main/resources/help/Indexed Encoder.html, src/main/resources/help/Introduction.html, src/main/resources/help/Limit Switch.html, src/main/resources/help/Mecanum Drive.html, src/main/resources/help/PID Controller.html, src/main/resources/help/PID Subsystem.html, src/main/resources/help/Quadrature Encoder.html, src/main/resources/help/Speed Controller Group.html, src/main/resources/help/Ultrasonic.html
=> Update links from screensteps to frc-docs

src/main/java/robotbuilder/RobotBuilder.java
Since command changes aren't included, file version is still
backwards compatible
=> Revert bumping file version to 3.0

src/main/java/robotbuilder/exporters/GenericExporter.java, src/main/resources/export/cpp/build.gradle, src/main/resources/export/java/build.gradle
Enable sim dependencies and fix typos
=> Update for wpilib Beta 4

.gitignore
Update to latest gitignore.io settings
=> Update .gitignore to ignore Visual Studio Code

src/main/resources/export/cpp/files.yaml, src/main/resources/export/java/files.yaml
=> Fix export of vendordep

src/main/resources/PaletteDescription.yaml, src/main/resources/help/Speed Controller.html
Add Talon FX and Venom. Update default.
Depends on wpilibsuite/allwpilib#2188
=> Update for 2020 speed controllers.

src/main/java/robotbuilder/exporters/GenericExporter.java, src/main/resources/export/cpp/wpilib_preferences.json, src/main/resources/export/java/wpilib_preferences.json
* Update ProjectYear to 2020
* Update wpilib version to v2020.1.2
=> Update ProjectYear to 2020

src/main/resources/PaletteDescription.yaml, src/main/resources/export/java/RobotContainer-constructors.java, src/main/resources/export/java/macros.vm
Only allow one timeout
Remove duplicate code for generating a command for JoystickButton and
SmartDashboard
Fix parameters when parameter preset not used
=> Improve command generation

src/main/resources/help/Mecanum Drive.html
Incorporated into other docs that were already linked
=> Remove Mecanum RB link to frc-docs

src/main/resources/export/java/ExportDescription.yaml, src/main/resources/export/java/PIDSubsystem-declarations.java, src/main/resources/export/java/Subsystem-constructors.java, src/main/resources/export/java/Subsystem-declarations.java
Fixes existing extensions. Fixes #236
=> Restore seperate declarations and construction

README.md, azure-pipelines.yml, build.gradle, src/main/resources/export/cpp/RobotContainer-buttons.cpp, src/test/java/robotbuilder/TestUtils.java, src/test/java/robotbuilder/exporters/CppExportTest.java
Temporarily disable wrist subsystem until PIDSubystem in C++ is fixed
(#263)
=> Add C++ Compile Test

src/main/resources/export/java/ExportDescription.yaml
A local variable was being created that hid the class variables.
This fixes the second bug mentioned in #260
=> Fix constructor of SpeedControllers

src/main/resources/export/cpp/build.gradle, src/main/resources/export/java/build.gradle
This matches wpilibsuite/vscode-wpilib#381
=> Enable driverstation sim extension by default

src/main/resources/export/wiring/ExportDescription.yaml, src/main/resources/export/wiring/files.yaml
=> Fix export of wiring file

src/main/java/robotbuilder/RobotBuilder.java, src/main/resources/export/cpp/wpilib_preferences.json, src/main/resources/export/gradle/settings.gradle, src/main/resources/export/java/settings.json, src/main/resources/export/java/wpilib_preferences.json
Its going to conflict with #281 but I started this before I saw that, and it does a few extra things. We can merge that first, and then I'll fix the conflicts.
=> Update to 2021 versions, fix vscode java projects

src/main/resources/export/java/PIDSubsystem.java, src/main/resources/export/java/Subsystem.java
PIDSubsystem periodic wasn't being called. Accidentally was called in subsystem instead.
=> Fix PIDSubsystem not running PIDController

src/main/resources/export/cpp/RobotContainer-autonomous.cpp, src/main/resources/export/cpp/RobotContainer.cpp
Also change from deprecated AddOption to SetDefaultOption
=> Put SendableChooser to SmartDashboard for C++

src/main/java/robotbuilder/robottree/RobotTree.java, src/test/java/robotbuilder/VersionTest.java
=> Fix version check allowing old versions to be opened

azure-pipelines.yml
=> Update publish to linux to fix line endings of scripts

src/main/resources/export/cpp/deploy_example.txt, src/main/resources/export/java/deploy_example.txt
=> Update deploy example files

src/main/resources/export/cpp/build.gradle, src/main/resources/export/java/build.gradle, src/main/resources/export/wpi/BSD_License_for_WPILib_code.txt
Copies wpilibsuite/vscode-wpilib#423 and wpilibsuite/vscode-wpilib#422
=> Update templates to match recent VS Code changes

.github/workflows/manual-publish.yml
This will allow anyone with write permission to manually publish
=> Add manual publish action

src/main/resources/export/cpp/ExportDescription.yaml, src/test/java/robotbuilder/TestUtils.java
Fixes #377
Fix test to generate Xbox Button
=> Fix C++ Export of Xbox Button

src/main/resources/export/java/ExportDescription.yaml
=> Fix declaration of SpeedControllerGroup

src/main/resources/export/cpp/RobotContainer-includes.h
=> Remove duplicate subsystem includes in RobotContainer

src/main/java/robotbuilder/exporters/ExportFile.java, src/main/java/robotbuilder/exporters/GenericExporter.java, src/main/java/robotbuilder/utils/CodeFileUtils.java, src/main/resources/export/parsers.yaml, src/test/java/robotbuilder/TestUtils.java, src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
=> Fix C++ Type detection

src/main/resources/export/java/ExportDescription.yaml
Fixes #396.
Fixes DoubleSolenoid, RobotDrive4, MecanumDrive, and Killough Drive.
=> Fix construction to avoid local copy

build.gradle
failed publish with gradle 7.1.1 and old artifactory plugin
=> Upgrade artifactory plugin

src/main/java/robotbuilder/data/properties/PositiveDoubleProperty.java, src/main/java/robotbuilder/utils/YamlUtils.java, src/main/resources/PaletteDescription.yaml, src/test/java/robotbuilder/data/properties/PositiveDoublePropertyTest.java
Fixes #218
Adds PositiveDoubleProperty that checks if >= 0.0
=> Only allow values >= 0 for timeout

src/main/resources/PaletteDescription.yaml
=> Fix XboxButton enums

src/main/resources/export/cpp/settings.json, src/main/resources/export/java/settings.json
Mirrors wpilibsuite/vscode-wpilib#509
=> Remove certificate workaround.

src/main/resources/export/java/ExportDescription.yaml, src/test/java/robotbuilder/TestUtils.java
Add test with DoubleSolenoid in its own subsystem
Fixes #464
=> Fix imports for DoubleSolenoid

src/main/resources/PaletteDescription.yaml, src/main/resources/export/cpp/RobotContainer-buttons.cpp, src/main/resources/export/java/RobotContainer-buttons.java
#472 Adds option to the Joystick Button and Xbox Button for add to SmartDashboard to reduce over population of widgets to Shuffleboard.
=> Add Option to Add Joystick buttons to SmartDashBoard

src/main/resources/export/java/build.gradle
Equivilent to wpilibsuite/vscode-wpilib#542
=> Add inline stringConcat to gradle java templates

src/main/resources/export/java/build.gradle
Equivilent to wpilibsuite/vscode-wplib#557
=> Update to Junit 5

src/main/java/robotbuilder/RobotBuilder.java, src/main/java/robotbuilder/data/properties/TeamNumberProperty.java, src/main/java/robotbuilder/utils/YamlUtils.java, src/main/resources/PaletteDescription.yaml, src/test/java/robotbuilder/data/properties/TeamNumberPropertyTest.java, src/test/java/robotbuilder/exporters/CppExportTest.java, src/test/java/robotbuilder/exporters/JavaExportTest.java
Create new TeamNumberProperty which checks > 0
This keeps someone from exporting a project with team number of 0.
Supersedes #505
=> Validate Team Number

src/main/resources/help/Xbox Button.html
Fixes wpilibsuite/BetaTest#140
=> Update XBox Button help for trigger changes

src/main/resources/export/java/build.gradle
Matches wpilibsuite/vscode-wpilib#568
=> Update Junit to 5.8.2 in robot templates

build.gradle
hanging for 30 min on Vex links and then failing
=> Temporarily disable link check

src/main/java/robotbuilder/data/properties/ConstantsProperty.java
=> Fix for Constants aliasing - Resolves #98

src/main/resources/export/cpp/build.gradle, src/main/resources/export/java/build.gradle
This reverts commit aab2945db908390bed0c6e678f05331801060600.
=> Revert "Use development WPILib builds"

src/main/resources/export/java/build.gradle
Matches wpilibsuite/vscode-wpilib#591
Fixes deprecation matching wpilibsuite/vscode-wpilib#602
=> Update java target and source compat to 17

README.md, azure-pipelines.yml
Update readme for JDK 17, and update C++ compiler instructions
=> Use JDK 17 for CI

src/main/resources/export/java/build.gradle
matches wpilibsuite/vscode-wpilib#589
=> Bundle java source with jar

src/main/resources/export/cpp/CommandBasedRobot.cpp, src/main/resources/export/java/RobotTemplate.java
default is now disabled in WPILib, enable to keep same behavior
=> Enable LiveWindow in Test by default

src/test/java/robotbuilder/TestUtils.java
DoubleSolenoid was double allocated
negative PID gain
=> Fix issues with test program

src/main/resources/export/cpp/build.gradle, src/main/resources/export/java/build.gradle
This reverts commit 0e6ee4a17eac1fe4731744e56596c237327f7367.
=> Revert "Use development WPILib builds (#586)"

src/main/resources/export/java/build.gradle
matches wpilibsuite/vscode-wpilib#647
=> Update to junit 5.10.1 for robot projects

.github/workflows/gradle-wrapper-validation.yml
Waiting for Gradle wrapper validation to release a stable version of the action
=> [ci] update actions versions

.github/workflows/0001-Disable-compile-tests-until-GradleRIO-released-.patch, .github/workflows/bump.yml, src/main/java/robotbuilder/exporters/GenericExporter.java
Disables export tests and updates hardcoded version prior to tagging 
Re-enables export tests after tagged
Fixes #212
=> Add action to tag on allwpilib tag dispatch

src/main/resources/export/java/build.gradle
Relies on https://github.com/wpilibsuite/GradleRIO/pull/744
=> Add annotation processors to Java build.gradle

.github/workflows/bump.yml
Check if tag already exists and don't do the version patch again
=> Fix version bump CI when allwpilib tag is slid

src/main/resources/export/cpp/settings.json
matches https://github.com/wpilibsuite/vscode-wpilib/pull/701
=> Add case sensitive file support to C++ projects

src/main/java/robotbuilder/utils/YamlUtils.java, src/test/java/robotbuilder/TestUtils.java
=> Add Tag and type description for ValuedParameterDescriptor

LICENSE.md, src/main/resources/export/wpi/BSD_License_for_WPILib_code.txt, src/main/resources/export/wpi/dot.gitignore
=> Update gitignore and license file

src/main/java/robotbuilder/DeprecatedDialog.java, src/main/java/robotbuilder/MainFrame.java, src/main/java/robotbuilder/RobotBuilder.java
=> Add popup that robotbuilder is deprecated
